// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrdersApp.Infrastructure.DataBaseContext;

#nullable disable

namespace OrdersApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230808072400_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrdersApp.Core.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderID = new Guid("1298c7c7-7355-47c9-9a6c-20fae1235e04"),
                            CustomerName = "Jane Mole",
                            OrderDate = new DateTime(2023, 8, 8, 10, 24, 0, 171, DateTimeKind.Local).AddTicks(3246),
                            OrderNumber = "ORD_0001",
                            TotalAmount = 42.200000000000003
                        },
                        new
                        {
                            OrderID = new Guid("bde74418-44bd-4bbc-a4cb-fcd1087010a9"),
                            CustomerName = "Chris Jankins",
                            OrderDate = new DateTime(2023, 8, 8, 10, 24, 0, 171, DateTimeKind.Local).AddTicks(3335),
                            OrderNumber = "ORD_0002",
                            TotalAmount = 22.199999999999999
                        });
                });

            modelBuilder.Entity("OrdersApp.Core.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("UnitPrice")
                        .IsRequired()
                        .HasColumnType("float");

                    b.HasKey("OrderItemID");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderItemID = new Guid("80192c06-c6da-4f14-acc5-5aaa944f0006"),
                            OrderID = new Guid("1298c7c7-7355-47c9-9a6c-20fae1235e04"),
                            ProductName = "Razor Keyboard",
                            Quantity = 5000,
                            UnitPrice = 8400.0
                        },
                        new
                        {
                            OrderItemID = new Guid("31143d81-5b90-4cf6-bcf6-13be124a8aba"),
                            OrderID = new Guid("1298c7c7-7355-47c9-9a6c-20fae1235e04"),
                            ProductName = "Razor Mouse",
                            Quantity = 5000,
                            UnitPrice = 2400.0
                        },
                        new
                        {
                            OrderItemID = new Guid("5d30db88-6ec9-49d3-ac09-b4a926fede2c"),
                            OrderID = new Guid("bde74418-44bd-4bbc-a4cb-fcd1087010a9"),
                            ProductName = "Samsung PC Screen",
                            Quantity = 1000,
                            UnitPrice = 3400.0
                        },
                        new
                        {
                            OrderItemID = new Guid("b6f94083-1c2d-49ca-930b-bca3cc1ee53b"),
                            OrderID = new Guid("bde74418-44bd-4bbc-a4cb-fcd1087010a9"),
                            ProductName = "HyperX Headphones",
                            Quantity = 500,
                            UnitPrice = 1400.0
                        },
                        new
                        {
                            OrderItemID = new Guid("8ae24980-58a4-49ed-8c65-5d3aca583801"),
                            OrderID = new Guid("bde74418-44bd-4bbc-a4cb-fcd1087010a9"),
                            ProductName = "ASUS Laptop",
                            Quantity = 1000,
                            UnitPrice = 10400.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
